services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # RabbitMQ messaging port
      - "15672:15672"  # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3307:3307"  # MySQL port
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Root password for MySQL
      MYSQL_DATABASE: db_aaf559_product  # Database name
      MYSQL_USER: aaf559_product  # MySQL username
      MYSQL_PASSWORD: syntec@123  # MySQL password
    volumes:
     - db-data:/var/lib/mysql  # Persist MySQL data
volumes:
      db-data:
